### PR TITLE
Feature/gp model

### PR DESCRIPTION
**Pull request by TomasBeuzen**
Added GP runup model, and updated tests and docs as necessary. The GP model only facilitates R2 prediction at present (although it can output a standard deviation which can be incorporated in future if desired). No infragravity component of swash predicted with this model.

### CODE REVIEW

**Comment by TomasBeuzen** [comment]
ps - sorry about the weird commit list. I got sucked into the dark depths of GitHub for a bit.

**Review by ebgoldstein — COMMENTED** [review]
hey look! I'm participating!.. actually I'm reading this to understand how to add the Passarrella et al 2018 IG swash predictor (which I'm not sure is allowed, since it doesn't do Runup, but it's still cool!)

**Comment by chrisleaman** [comment]
Yep, I'll eventually add Passarrella18 to the models as well. It won't have an R2 property, only the sig property so something like this:

``` python
class Passarrella2018(RunupModel):

    @property
    def sig(self):
        return ...
```

Btw, will get round to merging this PR in soon!

**Comment by ebgoldstein** [comment]
@chrisleaman I will add Passarrella18.... i would like to participate.. it's on my list of things to do

**Comment by TomasBeuzen** [comment]
Hahaha this is amazing! Go DREAM TEAM!

**Pull request merged**
